# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/16 17:33:20 by aaoutem-          #+#    #+#              #
#    Updated: 2023/11/24 10:23:12 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

compile = c++ -Wall -Wextra -Werror -std=c++98

build : megaphone.cpp
	$(compile) megaphone.cpp -o megaphone

clean :
	rm -rf megaphone
