# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/15 21:57:27 by aaoutem-          #+#    #+#              #
#    Updated: 2024/03/16 02:49:43 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

compile = c++ -Wall -Wextra -Werror -std=c++98

SRC = main.cpp
# HDR = Whatever.hpp

build : $(SRC) $(HDR)
	$(compile) $(SRC) -o main

clean : 
	rm main
