# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/12 16:10:02 by aaoutem-          #+#    #+#              #
#    Updated: 2023/11/23 11:58:32 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

exec =: Fixed

Compiler := c++ -std=c++98 -Wall -Wextra -Werror 

SRC := Fixed.cpp main.cpp

build : $(SRC)
	$(Compiler) $< -o Fixed
