# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/12 16:10:02 by aaoutem-          #+#    #+#              #
#    Updated: 2023/11/12 16:18:18 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

exec =: Fixed

Compiler := c++ -std=c++98 -Wall -Wextra -Werror 

SRC := Fixed.cpp main.cpp

all : $(exec)

$(exec) : $(SRC) 
	$(Compiler) $< -o exec




