# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/01 21:52:42 by aaoutem-          #+#    #+#              #
#    Updated: 2024/02/06 03:15:35 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Compile = c++ -Wall -Werror -Wextra -std=c++98

SRC = AForm.cpp PresidentialPardonForm.cpp RobotomyRequestForm.cpp \
		ShrubberyCreationForm.cpp main.cpp
HDR = AForm.hpp Bureaucrat.cppBureaucrat.hpp PresidentialPardonForm.hpp\
		RobotomyRequestForm.hpp ShrubberyCreationForm.hpp

build : $(SRC) $(HDR)
	$(Compile) $(SRC) 
	
# clean :
	