# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/12/06 20:56:52 by aaoutem-          #+#    #+#              #
#    Updated: 2023/12/06 20:57:42 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Compile = c++ -Wall -Wextra -Werror -std=c++98

SRC = Animal.cpp  Cat.cpp  Dog.cpp main.cpp

build : $(SRC)  Animal.hpp  Cat.hpp  Dog.hpp 
	$(Compile) $(SRC) 
	
# clean : 
# 	rm zoo