# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/02/01 21:52:42 by aaoutem-          #+#    #+#              #
#    Updated: 2024/03/07 02:32:45 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Compile = c++ -Wall -Werror -Wextra -std=c++98

SRC = main.cpp AForm.cpp ShrubberyCreationForm.cpp Bureaucrat.cpp\
		PresidentialPardonForm.cpp RobotomyRequestForm.cpp Intern.cpp
 
HDR = AForm.hpp  Bureaucrat.hpp PresidentialPardonForm.hpp\
		RobotomyRequestForm.hpp ShrubberyCreationForm.hpp Intern.hpp

build : $(SRC) $(HDR)
	$(Compile) $(SRC) 
	
# clean :
 