# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaoutem- <aaoutem-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/22 14:18:39 by aaoutem-          #+#    #+#              #
#    Updated: 2023/12/01 11:51:50 by aaoutem-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


Compile = c++ -Wall -Wextra -Werror -std=c++98

SRC = main.cpp Fixed.cpp

build : $(SRC) Fixed.hpp
	$(Compile) $(SRC) -o Fixed

clean :
	rm Fixed
